CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number VARCHAR(50) NOT NULL,
    room_type VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_rooms_room_number UNIQUE (room_number)
);

COMMENT ON TABLE rooms IS '외부 예약 시스템의 방 정보';
COMMENT ON COLUMN rooms.id IS '방 식별자';
COMMENT ON COLUMN rooms.room_number IS '외부 시스템에서 사용하는 방 번호';
COMMENT ON COLUMN rooms.room_type IS '방 타입. 예: STANDARD, DELUXE, SUITE';
COMMENT ON COLUMN rooms.status IS '방 상태. 예: AVAILABLE, MAINTENANCE';
COMMENT ON COLUMN rooms.created_at IS '방 정보 생성 일시';
COMMENT ON COLUMN rooms.updated_at IS '방 정보 마지막 수정 일시';

CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL,
    guest_name VARCHAR(100) NOT NULL,
    check_in_date DATE NOT NULL,
    check_out_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL,
    create_idempotency_key VARCHAR(100),
    cancel_idempotency_key VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cancelled_at TIMESTAMP,
    CONSTRAINT fk_reservations_room FOREIGN KEY (room_id) REFERENCES rooms (id),
    CONSTRAINT ck_reservations_dates CHECK (check_out_date > check_in_date),
    CONSTRAINT uk_reservations_create_idempotency_key UNIQUE (create_idempotency_key),
    CONSTRAINT uk_reservations_cancel_idempotency_key UNIQUE (cancel_idempotency_key)
);

COMMENT ON TABLE reservations IS '외부 예약 시스템의 예약 정보';
COMMENT ON COLUMN reservations.id IS '예약 식별자';
COMMENT ON COLUMN reservations.room_id IS '예약된 방 식별자';
COMMENT ON COLUMN reservations.guest_name IS '예약자 이름';
COMMENT ON COLUMN reservations.check_in_date IS '체크인 날짜';
COMMENT ON COLUMN reservations.check_out_date IS '체크아웃 날짜';
COMMENT ON COLUMN reservations.status IS '예약 상태. 예: CONFIRMED, CANCELLED';
COMMENT ON COLUMN reservations.create_idempotency_key IS '예약 생성 요청의 멱등성 키';
COMMENT ON COLUMN reservations.cancel_idempotency_key IS '예약 취소 요청의 멱등성 키';
COMMENT ON COLUMN reservations.created_at IS '예약 생성 일시';
COMMENT ON COLUMN reservations.updated_at IS '예약 마지막 수정 일시';
COMMENT ON COLUMN reservations.cancelled_at IS '예약 취소 일시';

CREATE INDEX idx_reservations_room_dates
    ON reservations (room_id, check_in_date, check_out_date, status);

CREATE TABLE idempotency_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(100) NOT NULL,
    operation_type VARCHAR(30) NOT NULL,
    resource_type VARCHAR(50) NOT NULL,
    resource_id BIGINT,
    request_hash VARCHAR(128),
    response_payload CLOB,
    http_status INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_idempotency_records_key UNIQUE (idempotency_key)
);

COMMENT ON TABLE idempotency_records IS '멱등성 키 기반 중복 요청 처리 기록';
COMMENT ON COLUMN idempotency_records.id IS '멱등성 기록 식별자';
COMMENT ON COLUMN idempotency_records.idempotency_key IS '클라이언트가 요청 헤더로 전달한 멱등성 키';
COMMENT ON COLUMN idempotency_records.operation_type IS '멱등성이 적용된 작업 타입. 예: CREATE_RESERVATION, CANCEL_RESERVATION';
COMMENT ON COLUMN idempotency_records.resource_type IS '작업 대상 리소스 타입. 예: RESERVATION';
COMMENT ON COLUMN idempotency_records.resource_id IS '작업으로 생성되거나 변경된 리소스 식별자';
COMMENT ON COLUMN idempotency_records.request_hash IS '같은 멱등성 키로 다른 요청 본문이 들어오는지 검증하기 위한 요청 해시';
COMMENT ON COLUMN idempotency_records.response_payload IS '최초 처리 시 반환한 응답 본문';
COMMENT ON COLUMN idempotency_records.http_status IS '최초 처리 시 반환한 HTTP 상태 코드';
COMMENT ON COLUMN idempotency_records.created_at IS '멱등성 기록 생성 일시';
COMMENT ON COLUMN idempotency_records.updated_at IS '멱등성 기록 마지막 수정 일시';
